schema_version = "1.0.0"

id = "laserity"
version = "0.1.0"
name = "Laserity"
tagline = "Export flat parts to SVG for laser cutting"
maintainer = "Sławomir Sobczak <studiomedio.com@gmail.com>"
type = "add-on"

website = "https://github.com/studiomedio/blender-laserity"
tags = ["Import-Export", "Mesh"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Write the exported SVG sheets to disk"
